# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collapsed_lda_cpp <- function(data, alpha, beta, K, thin, niter, warmup, keep_index, verbose) {
    .Call(`_EFLDA_collapsed_lda_cpp`, data, alpha, beta, K, thin, niter, warmup, keep_index, verbose)
}

collapsed_efd_cpp <- function(data, alpha, beta, tau, p, K, thin, niter, warmup, keep_index, verbose) {
    .Call(`_EFLDA_collapsed_efd_cpp`, data, alpha, beta, tau, p, K, thin, niter, warmup, keep_index, verbose)
}

