# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

whichOne <- function(x) {
    .Call(`_EFLDA_whichOne`, x)
}

whichC <- function(x, val) {
    .Call(`_EFLDA_whichC`, x, val)
}

oneMultinomC <- function(probs) {
    .Call(`_EFLDA_oneMultinomC`, probs)
}

cmultinom <- function(probs, d = 0L, w = 0L) {
    .Call(`_EFLDA_cmultinom`, probs, d, w)
}

isInVector <- function(value, vec) {
    .Call(`_EFLDA_isInVector`, value, vec)
}

collapsed_lda_cpp <- function(data, alpha, beta, K, niter, keep_index, z_init, verbose, nupd = 0L) {
    .Call(`_EFLDA_collapsed_lda_cpp`, data, alpha, beta, K, niter, keep_index, z_init, verbose, nupd)
}

collapsed_efd_cpp <- function(data, alpha, beta, tau, p, K, niter, keep_index, z_init, verbose, nupd = 0L) {
    .Call(`_EFLDA_collapsed_efd_cpp`, data, alpha, beta, tau, p, K, niter, keep_index, z_init, verbose, nupd)
}

collapsed_lda_cpp_pred <- function(data, alpha, beta, phi_post_mean, K, niter, keep_index, z_init, verbose, nupd = 0L) {
    .Call(`_EFLDA_collapsed_lda_cpp_pred`, data, alpha, beta, phi_post_mean, K, niter, keep_index, z_init, verbose, nupd)
}

collapsed_efd_cpp_pred <- function(data, alpha, beta, tau, p, phi_post_mean, K, niter, keep_index, z_init, verbose, nupd = 0L) {
    .Call(`_EFLDA_collapsed_efd_cpp_pred`, data, alpha, beta, tau, p, phi_post_mean, K, niter, keep_index, z_init, verbose, nupd)
}

